version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    rebase-strategy: auto
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "deps"
      include: scope
    labels:
      - dependencies
      - javascript
    groups:
      weekly-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
      day: tuesday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: "ci"
      include: scope
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"
