blank_issues_enabled: true
contact_links:
  - name: Need ZAP-Hosting server support?
    url: https://zap-hosting.com/en/customer/support/
    about: Please create a ticket on our website to contact support.